<a href="https://colab.research.google.com/github/abiramig1821-pixel/Python-Numpy-and-Pandas-Assignment1/blob/main/Python_Assignment1_Numpy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python DA Assignment 1—Numpy and Pandas**

## **Overview:**

This assignment focuses on performing data analysis using NumPy and Pandas.
   
  The objective is to:

    ● Work with NumPy arrays for numerical computations

    ● Use Pandas Series and DataFrame for data manipulation and analysis

    ● Apply indexing, slicing, filtering, and aggregation techniques

    ● Understand real-world data handling through temperature and transaction datasets


will analyze temperature data using NumPy and perform structured data analysis using Pandas.

## **Tasks:**

*  **Numpy Array Operations**
    1. Create a 1D NumPy Array
    2. Inspection and Properties
    3. Array Operations
    4. Array Slicing and Indexing
    5. Create a 2D Array
    6. Inspect and Slice the 2D Array

*  **Pandas Series**
    1. Creating Pandas Series
    2. Indexing and Slicing
    3. Manipulating Series

*  **Pandas DataFrame**
    1. Creating Pandas DataFrame
    2. Data Exploration
    3. Manipulating the DataFrame

### **Numpy Array Operations:**

**Scenario:**

You are given a list of daily average temperatures (in degrees Celsius) recorded over two weeks. Your task is to use NumPy to analyze this data.



**1. Create a 1D NumPy Array:**

Create a 1D NumPy array named temperatures_w1 for Week 1 with the following
values:
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

In [4]:
# Import numpy and pandas
import numpy as np
import pandas as pd

In [5]:
temp = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

temperatures_w1 = np.array(temp)
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

**2. Inspection and Properties:**

* Inspect the shape, data type, and the number of elements in the array.

* Inspect the shape of the temperatures_w1 array.

In [6]:
# Inspect the shape, data type, and the number of elements in the array.

# Shape
temperatures_w1.shape

(7,)

In [7]:
# Data type

type(temperatures_w1)

numpy.ndarray

In [8]:
# number of elements in the array.

temperatures_w1.size

7

**3. Array Operations:**

    ● Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:

      Fahrenheit = (Celsius * 9/5) + 32

    ● Find the maximum, minimum, and mean temperatures for the week.

In [9]:
# Convert the temperatures_w1 from Celsius to Fahrenheit using the formula:
# Fahrenheit = (Celsius * 9/5) + 32

temp_cel = temperatures_w1*9/5+32
temp_cel

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [10]:
# Find the maximum, minimum, and mean temperatures for the week.

# Minimum temperature for the week

Min_temp= np.min(temp_cel)
Min_temp

np.float64(69.44)

In [11]:
# Maximum temperature for the week
Max_temp= np.max(temp_cel)
Max_temp

np.float64(78.98)

In [12]:
# Mean temperature for the week
avg_temp= np.average(temp_cel)
avg_temp

np.float64(74.37714285714286)

**4. Array Slicing and Indexing:**

    ● Extract the temperatures for the first three days of the week.

    ● Extract the temperatures for the weekend (last two days).

    ● Extract the temperatures for the middle three days of the week.

In [13]:
# Extract the temperatures for the first three days of the week.

temp_cel[0:3]

array([72.5 , 77.54, 69.44])

In [14]:
# Extract the temperatures for the weekend (last two days).

temp_cel

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [15]:
temp_cel[-2:]

array([76.64, 71.42])

In [16]:
# Extract the temperatures for the middle three days of the week.
temp_cel.size

7

In [17]:
temp_cel[2:5]

array([69.44, 74.12, 78.98])

**5. Create a 2D Array:**

Create a 2D NumPy array named temperatures where each row represents
temperatures for a different week:

    ★ Row 1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] (Week 1)

    ★ Row 2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] (Week 2)

In [18]:
# Create a 2D NumPy array named temperatures where each row represents temperatures for a different week:
temp_2=[[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
            [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]]

temp_2darr =np.array(temp_2)
type(temp_2darr)

numpy.ndarray

**6. Inspect and Slice the 2D Array:**

    ● Inspect and print the shape, data type, and total number of elements in the temperatures array.

    ● Extract the temperatures for each week and the weekends (last two days) for both weeks.

In [19]:
# Inspect and print the shape, data type, and total number of elements in the temperatures array.

# shape
temp_2darr.shape

(2, 7)

In [20]:
# data type
type(temp_2darr)

numpy.ndarray

In [21]:
# total number of elements in the temperatures array.
temp_2darr.size

14

### **Pandas Series:**

**1. Creating Pandas Series:**

    ● Create a Pandas Series named marks with the following data:

        ➢ Marks: 95, 92, 89, 85, 80
        
        ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

In [22]:
# Create a Pandas Series named marks with the following data:

import pandas as pd

mark = [95, 92, 89, 85, 80]
Marks_ser = pd.Series(mark)
Marks_ser

,0
0,95
1,92
2,89
3,85
4,80


In [23]:
#  ➢ Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'
Marks_ser =pd.Series(mark,index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'], name='marks')
Marks_ser


,marks
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


**2. Indexing and Slicing:**

    ● Use the integer index position to access the mark of the 1st rank student.

    ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

    ● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

    ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

In [24]:
# Use the integer index position to access the mark of the 1st rank student.

Marks_ser['Rank1']

np.int64(95)

In [25]:
# Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

Marks_ser.loc['Rank1':'Rank3']

,marks
Rank1,95
Rank2,92
Rank3,89


In [26]:
# Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

print(Marks_ser.iloc[2])

89


In [27]:
# Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

mask = Marks_ser>90
mask
fillter_markseries = Marks_ser[mask]
fillter_markseries

,marks
Rank1,95
Rank2,92


**3. Manipulating Series:**

      ● Modify the mark of the student with the 1st rank to 100.

      ● Remove the entry corresponding to the last rank from the Series.

      ● Compute the CGPA by dividing each mark in the Series by 10.

In [28]:
# Modify the mark of the student with the 1st rank to 100.

Marks_ser['Rank1']=100
Marks_ser

,marks
Rank1,100
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [29]:
# Remove the entry corresponding to the last rank from the Series.

Marks_ser.drop(Marks_ser.index[-1])

,marks
Rank1,100
Rank2,92
Rank3,89
Rank4,85


In [30]:
# Compute the CGPA by dividing each mark in the Series by 10

CGPA= Marks_ser/10
CGPA

,marks
Rank1,10.0
Rank2,9.2
Rank3,8.9
Rank4,8.5
Rank5,8.0


### **Pandas DataFrame:**

**1. Creating Pandas DataFrame:**

    ● Create a Pandas DataFrame named transactions with the following data:   
    
      ➢TransactionID: 101, 102, 103, 104, 105, 106, 107, 108, 109, 110

      ➢ ProductCategory: 'Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing',
      'Furniture', 'Electronics'
      
      ➢ Region: 'North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'
      
      ➢ Amount: 200, 150, 300, 450, 200, 250, 300, 180, 350, 400

In [31]:
# Create DataFrame
Trans = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture','Clothing', 'Furniture', 'Electronics'],
    'Region':['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'],
    'Amount':[200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}

Transaction = pd.DataFrame(Trans)
Transaction


,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


**2. Data Exploration:**

    ● Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
    
    ● Display only the 'ProductCategory' and 'Amount' columns.
    
    ● Retrieve the last 3 columns of the DataFrame using iloc or loc.
    
    ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.
    
    ● Find the value counts for the 'ProductCategory' column.
    
    ● Find the unique values in the 'Region' column.
    
    ● Group by 'Region' and find the mean amount for each region.

In [32]:
# Display the transactions DataFrame and its basic information, including head, tail, shape, column names, and data types.
# Info()
Transaction.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   TransactionID    10 non-null     int64 
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [144]:
# Head()
Transaction.head()

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [33]:
# Tail()

Transaction.tail()

,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [34]:
# Datatypes
Transaction.dtypes

,0
TransactionID,int64
ProductCategory,object
Region,object
Amount,int64


In [35]:
# shape
Transaction.shape

(10, 4)

In [36]:
Transaction.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [37]:
Transaction.select_dtypes(include='number').columns

Index(['TransactionID', 'Amount'], dtype='object')

In [38]:
# Display only the 'ProductCategory' and 'Amount' columns.

Transaction.iloc[::,1:5:2]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [43]:
Transaction

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [49]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.

Transaction.iloc[::,-3:]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [65]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

Transaction[(Transaction['Region'] == 'North') & (Transaction['Amount'] > 200)]


,TransactionID,ProductCategory,Region,Amount
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [66]:
# Find the value counts for the 'ProductCategory' column.

Transaction['ProductCategory'].value_counts()

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


In [68]:
# Find the unique values in the 'Region' column.

Transaction['Region'].nunique()

4

In [74]:
Transaction.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [77]:
# Group by 'Region' and find the mean amount for each region.

Transaction.groupby("Region")['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


**3. Manipulating the DataFrame:**

    ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

    ● Add a new column 'Discount' by calculating 10% of the 'Amount'.

    ● Remove the row with TransactionID 109.

    ● Delete the 'Discount' column from the DataFrame.

In [102]:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165.


Transaction.loc[Transaction['TransactionID'] == 102, 'Amount'] = 165
Transaction

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [103]:
# Add a new column 'Discount' by calculating 10% of the 'Amount'.

Transaction["Discount"]=Transaction['Amount']*0.10
Transaction

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [94]:
# Remove the row with TransactionID 109.
Transaction.drop(Transaction[Transaction['TransactionID']==109].index, inplace=True)
Transaction

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0
Amount,200,200,200,200,20.0


In [110]:
# Delete the 'Discount' column from the DataFrame.

Transaction.drop(columns=['Discount'],inplace=True,errors='ignore')
Transaction

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400
